### ISSUE TITLE
Questions from 2021 new MeSH E-F, G-I, J-L  (GWN)

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/mapping-project#1]
Mostly I'm looking to double check some of my decisions, especially when I decided there wasn't a good LSCH match:

- MH - Elevated Plus Maze Test -> NO MATCH
- MH - Embolic Stroke -> NO MATCH
- MH - Exiguobacterium -> NO MATCH (use broader term for LSCH Gram-negative bacteria?)
- MH - Fonsecaea -> NO MATCH
- MH - Food Deserts -> NO MATCH (map to Broader LSCH Food security?) (Note: mapped Food Security -> Food security already)
- MH - Food Insecurity -> NO MATCH (map to Broader LSCH Food security?) (Note: mapped Food Security -> Food security already)
- MH - Functional Status -> NO MATCH (Health status indicators was closest in LCSH, but that is already a 1:1 term in MeSH)
- MH - Fungal Genus Humicola -> NO MATCH
- MH - Gender Role -> Sex role (both of these also mapped to "Gender identity" in both MeSH and LSCH)
- MH - HaCaT Cells -> NO MATCH
- MH - Heart Disease Risk Factors -> Coronary heart disease--Risk factors (Check this one - mapped one MeSH to complex LCSH (but one with its own number) - should this be mapped to both the main term and the subdivision instead?)
- MH - Heteroplasmy -> NO MATCH (would like a second opinion on this)
- MH - Host Adaptation -> NO MATCH (would others do a broader mapping to LCSH Adaptation (Biology)?)
- MH - Hyperferritinemia - NO MATCH
- MH - Hyperthermia -> Would folks map to Fever (which already maps to MeSH Fever)? There doesn't seem to be a non-pathologic hyperthermia term in LCSH.
- MH - Hyperthermic Intraperitoneal Chemotherapy -> unsure - look for a Chemothereapy AND, or NO MATCH? I don't think I can come up with just two LCSH terms
- MH - Identity Recognition -> unsure about this one too. There are already MeSH and LCSH matching terms "Biometric Identification" and LCSH doesn't seem to have a term that gets at the "ability to identify"
- MH - Immune Checkpoint Inhibitors -> NO MATCH
- MH - Immune Checkpoint Proteins -> See above, but also struggling with this one. Immunological Adjuvants (both MeSH and LCSH) doesn't seem to fit. Use that AND Proteins, or NO MATCH?
- MH - Induced Demand -> NO MATCH
- MH - Internet Use -> ??? closest I can get is Internet users, but that doesn't seem equivalent
- MH - Ischemic Stroke -> NO MATCH (though considering Cerebrovascular disease AND Cerebral ischemia?)
- MH - Kimura Disease -> NO MATCH
- MH - Laminopathies -> NO MATCH
- MH - Liberibacter -> NO MATCH

Not tagging anyone as a test to see how notification works.

**Comment by sharonwilliss** [comment]
•	MH - Elevated Plus Maze Test -> NO MATCH
Sharon’s response: per MeSH BT is Maze Learning (has Entry Term Maze Test).  Maze tests is in LCSH.  Could map Elevated Plus Maze Test as NT to LCSH Maze tests
•	MH - Embolic Stroke -> NO MATCH Sharon’s Response:  agree no match
Just an observation: the MeSH Parent term is Stroke which is not mapped in MeSH to LCSH mapping file.  LCSH has Stroke as variant term to Cerebrovascular disease.  LSCH Cerebrovascular disease is mapped correctly to MeSH Cerebrovascular Disorders.  However MeSH record for Cerebrovascular Disorders has obsolete 550s, one of which is Stroke.  Question:  Does it matter that 450s/550s are not up to date in the GitHub mapping files?
•	MH - Exiguobacterium -> NO MATCH (use broader term for LSCH Gram-negative bacteria?)
Sharon’s response: per MeSH BT is Bacillaceae.  Bacillaceae is in LCSH.  Could map Exiguobacterium as NT to LCSH Bacillaceae
•	MH - Fonsecaea -> NO MATCH
Sharon’s response: per MeSH BT is Ascomycota. Ascomycota is in LCSH as variant to Ascomycetes.  Could map Fonsecaea as NT to LCSH Ascomycetes
•	MH - Food Deserts -> NO MATCH (map to Broader LSCH Food security?) (Note: mapped Food Security -> Food security already)
Sharon’s response: per MeSH BT is Food Supply. Food Deserts is variant in LCSH to Food security which as you note is already mapped to MeSh Food Security.  Not sure if it correct to Food Deserts as NT to LCSH Food security.  Not sure if it should be mapped as NT to LSCH Food supply or just not mapped at all
•	MH - Food Insecurity -> NO MATCH (map to Broader LSCH Food security?) (Note: mapped Food Security -> Food security already)
Sharon’s response: per MeSH BT is Food Supply. Food Insecurity is variant in LCSH to Food security which as you note is already mapped to MeSh Food Security.  Not sure if it correct to Food Insecurity as NT to LCSH Food security.  Not sure if it should be mapped as NT to LSCH Food supply or just not mapped at all
•	MH - Functional Status -> NO MATCH (Health status indicators was closest in LCSH, but that is already a 1:1 term in MeSH)
Sharon’s response:  Would not map.  Per MeSH Health Status is BT.  NF in LCSH.  Health Status Indicators are different type of subject heading
•	MH - Fungal Genus Humicola -> NO MATCH Sharon’s Response:  agree no match
•	MH - Gender Role -> Sex role (both of these also mapped to "Gender identity" in both MeSH and LSCH)
Sharon’s response: Gender role is a variant on LCSH Sex role.  Shouldn’t this just be one-to-one mapping? The 750  \0$aSex role$5IEN-HS$0(DLC)sh 85120663 on 150  \\$aGender Identity in the MeSH mapping file should be removed.
•	MH - HaCaT Cells -> NO MATCH Sharon’s Response:  agree no match
•	MH - Heart Disease Risk Factors -> Coronary heart disease--Risk factors (Check this one - mapped one MeSH to complex LCSH (but one with its own number) - should this be mapped to both the main term and the subdivision instead?)
Sharon’s response: Not sure about this one.  Don’t think I would map it. Per MeSH, Coronary Disease is a narrower term than Heart Diseases.  Not sure about correct way to map to LCSH subdivisions although I do see an example on Northwestern’s example list
•	MH - Heteroplasmy -> NO MATCH (would like a second opinion on this) Sharon’s response: don’t see a match
•	MH - Host Adaptation -> NO MATCH (would others do a broader mapping to LCSH Adaptation (Biology)?)
Sharon’s response: Host Adaptation has 2 BTs in MeSH: Adaptation, Biological and Host-Pathogen Interactions (which has no corresponding LCSH).  Not sure I would map this.
•	MH - Hyperferritinemia - NO MATCH
Sharon’s response: Per MeSH, BT is Iron Metabolism Disorders.  LCSH has Iron--Metabolism—Disorders.  Not sure if worth mapping Hyperferritinemia as NT to it.
•	MH - Hyperthermia -> Would folks map to Fever (which already maps to MeSH Fever)? There doesn't seem to be a non-pathologic hyperthermia term in LCSH.
Sharon’s response: Would not map.  Fever is sibling to Hyperthermia in MeSH
•	MH - Hyperthermic Intraperitoneal Chemotherapy -> unsure - look for a Chemothereapy AND, or NO MATCH? I don't think I can come up with just two LCSH terms
Sharon’s response: Would not map
•	MH - Identity Recognition -> unsure about this one too. There are already MeSH and LCSH matching terms "Biometric Identification" and LCSH doesn't seem to have a term that gets at the "ability to identify"
Sharon’s response: Would not map
•	MH - Immune Checkpoint Inhibitors -> NO MATCH Sharon’s response: Agree no match
•	MH - Immune Checkpoint Proteins -> See above, but also struggling with this one. Immunological Adjuvants (both MeSH and LCSH) doesn't seem to fit. Use that AND Proteins, or NO MATCH?
Sharon’s response: don’t think there is a match
•	MH - Induced Demand -> NO MATCH Sharon’s response: Agree no match
•	MH - Internet Use -> ??? closest I can get is Internet users, but that doesn't seem equivalent Sharon’s response: Not the same.  No match
•	MH - Ischemic Stroke -> NO MATCH (though considering Cerebrovascular disease AND Cerebral ischemia?) Sharon’s response: See comment under Embolic Stroke.  This is not straightforward mapping
•	MH - Kimura Disease -> NO MATCH Sharon’s response: Agree no match
•	MH - Laminopathies -> NO MATCH Sharon’s response: Agree no match
•	MH - Liberibacter -> NO MATCH 
Sharon’s response: per MeSH BT is Rhizobiaceae.  Could map Liberibacter as NT to LCSH Rhizobiaceae

**Comment by gneidhardt** [comment]
Made edits as suggested.
