### ISSUE TITLE
Questions from 2021 new MeSH M-O (GWN)

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/mapping-project#2]
Some questions about items that I didn't find exact matches for (and some possible alternatives to no match):

- MH  - Mast Cell Stabilizers (D000082142) -> BM Mast cells (or NO MATCH)???
- MH  - Mediterranea (D000086222) -> NO MATCH
- MH  - Microvascular Density (D000082644) -> NO MATCH
- MH  - Mitochondrial Permeability Transition Pore (D000083162) -> NO MATCH
- MH  - Models, Biopsychosocial (D000086342)-> NO MATCH??? (this is under MeSH Models, Theoretical, which maps to LCSH Mathematical models, which doesn't seem like an appropriate broader term. Maybe BM LCSH Mental health--Study and teaching?)
- MH  - Nasoalveolar Molding (D000084982) -> BM Cleft palate services??? (sh85026928) OR BM Mouth--Abnormalities--Surgery (not an official LC term)???
- MH  - Neglecta (D000086242) -> NO MATCH
- MH  - Nocardioides (D000083962) -> NO MATCH
- MH  - Nocardiopsis (D000086262) -> NO MATCH
- MH  - Orientia (D000084162) -> NO MATCH
- MH  - Ovarian Torsion (D000082843) -> NO MATCH

**Comment by sharonwilliss** [comment]
•	MH - Mediterranea (D000086222) -> NO MATCH
Sharon’s response: per MesH, BT is [Bacteroidaceae [B03.440.080.094]](https://meshb.nlm.nih.gov/record/ui?ui=D001438).  LC has Bacteroidaceae https://id.loc.gov/authorities/subjects/sh85010881.html  Could map Mediterranea to Bacteroidaceae as NT (or not map at all)
•	MH - Microvascular Density (D000082644) -> NO MATCH
Sharon’s response: MH BT is [Cardiovascular Physiological Phenomena [G09.330]](https://meshb.nlm.nih.gov/record/ui?ui=D002320).  Search of “density” in LCSH yields no comparable match. Agree no match
•	MH - Mitochondrial Permeability Transition Pore (D000083162) -> NO MATCH Sharon’s Response:  agree no match
•	MH - Models, Biopsychosocial (D000086342)-> NO MATCH??? (this is under MeSH Models, Theoretical, which maps to LCSH Mathematical models, which doesn't seem like an appropriate broader term. Maybe BM LCSH Mental health--Study and teaching?)
Sharon’s response: Technically Models, Biopsychosocial is a NT to LCSH Mathematical models even though looks strange.  MS: “A systematic integration of biological, psychological, and social approaches to the study of mental health and specific mental disorders.”  LCSH Mental health--Study and teaching sounds better however not sure how far we are to go with contrived mapping
•	MH - Nasoalveolar Molding (D000084982) -> BM Cleft palate services??? (sh85026928) OR BM Mouth--Abnormalities--Surgery (not an official LC term)???
Sharon’s Response:  MH BT [Preoperative Care [E02.760.795]](https://meshb.nlm.nih.gov/record/ui?ui=D011300) MS: “A presurgical facial orthotic treatment for patients with bilateral and unilateral [CLEFT LIP](https://meshb.nlm.nih.gov/record/ui?ui=D002971) and [CLEFT PALATE](https://meshb.nlm.nih.gov/record/ui?ui=D002972).”  Cleft palate services??? (sh85026928) is very generic.  Would not make up LCSH. Do not map
•	MH - Neglecta (D000086242) -> NO MATCH Sharon’s Response:  agree no match
•	MH - Nocardioides (D000083962) -> NO MATCH
Sharon’s response: per MeSH BT is Actinobacteria.  Actinobacteria is in LCSH.  Could map Nocardioides as NT to LCSH Actinobacteria
•	MH - Nocardiopsis (D000086262) -> NO MATCH
Sharon’s response: per MeSH BT is Actinobacteria.  Actinobacteria is in LCSH.  Could map Nocardiopsis as NT to LCSH Actinobacteria
•	MH - Orientia (D000084162) -> NO MATCH Sharon’s Response:  agree no match
•	MH - Ovarian Torsion (D000082843) -> NO MATCH Sharon’s Response:  agree no match

**Comment by gneidhardt** [comment]
Made edits as suggested.
