### ISSUE TITLE
MeSH 2022 revisions - questions

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/mapping-project#7]
My questions are mostly of the "this didn't map to LCSH - would someone mind confirming" variety, but there were two other minor issues I wanted to share for feedback. One was "Pimenta", which seemed to already be mapped but I wanted to make sure I wasn't missing something. The other was the Native Hawaiian or Other Pacific Islander term, which had been mapped to Aboriginal Australians. This didn't seem right with the scope, so I adopted the solution described below.

D000075803 (not mapped - no match in LCSH)
MH OLD = Angiopoietin-like 4 Protein []
MH NEW = Angiopoietin-Like Protein 4

D048149 (not mapped - no match in LCSH)
MH OLD = Casein Kinase Iepsilon [P]
MH NEW = Casein Kinase 1 epsilon

D003765 (not mapped - no match in LSCH)
MH OLD = Dental Models [P]
MH NEW = Models, Dental

D000080309 (not mapped - no match in LSCH)
MH OLD = Environmental DNA [P]
MH NEW = DNA, Environmental

D027841 (already mapped - just want to make sure I'm not missing anything?)
MH OLD = Genus Pimenta []
MH NEW = Pimenta

D044468
MH OLD = Oceanic Ancestry Group [P]
MH NEW = Native Hawaiian or Other Pacific Islander
NOTE: I split this into two since previous mapping of Oceanic Ancestry  Group was to Aboriginal Australians (and current usage seems to imply that D044468 should map to Americans with Pacific Islander/Hawaiian ancestry)
-MeSH Native Hawaiian or Other Pacific Islander maps to LCSH Narrower Mappings Pacific Islander Americans OR Hawaiians
-MeSH Oceanians maps to LCSH Narrower Mappings Aboriginal Australians OR Pacific Islanders

D017346 (not mapped - no match in LCSH)
MH OLD = Protein-Serine-Threonine Kinases [P]
MH NEW = Protein Serine-Threonine Kinases

D057170 (not mapped - no match in LCSH)
MH OLD = Translational Medical Research [P]
MH NEW = Translational Research, Biomedical

**Comment by LindseyOB** [comment]
I checked these over and my only suggestion is on Dental Models.

Would you consider mapping to Mouth $x Models or Teeth $x Models?

**Comment by gneidhardt** [comment]
I like both of these suggestions! I will map them.
