### ISSUE TITLE
New MeSH 2022 E-H questions

### ISSUE THREAD

**Issue by gneidhardt** [galterlibrary/mapping-project#9]
MH  - Elite Controllers (not mapped - no match in LCSH)
UI  - D000088064

MH  - Ex utero Intrapartum Treatment Procedures (not mapped - no match in LCSH)
UI  - D000088103

MH  - Fractional Exhaled Nitric Oxide Testing (not mapped - no match in LCSH)
UI  - D000089142

MH  - Gaslighting (not mapped - no match in LCSH)
UI  - D000090206

MH  - Genitourinary Agents  (not mapped - no match in LCSH)
UI  - D000089162

MH  - Germ Cell Ribonucleoprotein Granules (not mapped - no match in LCSH)
UI  - D000088262

MH  - HCV NS3-4A Protease Inhibitors -> TWO Protease inhibitors (sh85107684) AND Hepatitis C virus (sh94002666) (would like a double check on this on - not totally sure if this works)
UI  - D000088802

MH  - Health Disparity, Minority and Vulnerable Populations (not mapped - no match in LCSH)
UI  - D000091202

MH  - Haptic Technology (not mapped - no match in LCSH)
UI  - D000089862

MH  - Hippo Signaling Pathway (not mapped - no match in LCSH)
UI  - D000090683

MH  - Home Environment (not mapped - no match in LCSH)
UI  - D000091502

MH  - Homeobox Protein Nkx-2.2 (not mapped - no match in LCSH)
UI  - D000090322

MH  - Hospital to Home Transition (not mapped - no match in LCSH)
UI  - D000088745

MH  - Housing Instability (not mapped - no match in LCSH) (seems like there should be a match?)
UI  - D000091003

MH  - Housing Quality (not mapped - no match in LCSH) (seems like there should be a match?)
UI  - D000091522

**Comment by sharonwilliss** [comment]
@gneidhardt I agree with your decisions not to map; I would not map HCV NS3-4A Protease Inhibitors .  Sharon

**Comment by gneidhardt** [comment]
thank you @sharonwilliss! I'm going to close this now as complete, but if others have comments I can always reopen
